{% set name = "dargs" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 95f3085dc912af4bcefbd38ced60717f023b7b59ff9ce6aadabfaceca2f11243

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm

  run:
    - python >=3.7
    - typeguard >=4
    - typing_extensions

test:
  requires:
    - pip
  imports:
    - dargs
  commands:
    - python -m pip check dargs

about:
  home: https://github.com/deepmodeling/dargs
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Process arguments for the deep modeling project.
  doc_url: https://github.com/deepmodeling/dargs
  dev_url: https://github.com/deepmodeling/dargs

extra:
  recipe-maintainers:
    - njzjz
