{% set name = "dargs" %}
{% set version = "0.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2907c4842a68585d3080bd0b9999e9ae6b68985d1a485365073d7cd9f5ec0fe4

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - dargs = dargs.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - typeguard >=4
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - dargs
  commands:
    - python -m pip check dargs
    - dargs -h

about:
  home: https://github.com/deepmodeling/dargs
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Process arguments for the deep modeling project.
  doc_url: https://github.com/deepmodeling/dargs
  dev_url: https://github.com/deepmodeling/dargs

extra:
  recipe-maintainers:
    - njzjz
